### ISSUE TITLE
Visual Glitch: Display issues on statistics page

### ISSUE THREAD

**Issue by schuylermartin45** [Z-KO/CSH-Android-Drink#6]
I think this screen shot speaks for itself:
http://imgur.com/90HM0Ez

If you rotate the wheel, it doesn't get any more readable

**Comment by zujko** [comment]
Yeah this is an issue with the [charting library](https://github.com/PhilJay/MPAndroidChart) I'm using. Their sample also does the same thing. Once I find a library that can do pie charts well, I'm going to replace the current one.

**Comment by schuylermartin45** [comment]
If possible, I'd say it probably makes the most sense to only draw the percents on the pie chart and then the names could be displayed in a dialog box upon clicking a section of the graph.

**Comment by zujko** [comment]
Yeah that is a cool idea but I feel like it would be tedious/annoying to the user if they had to click on the section just to see the name. Plus some of the sections can get really small and it would be difficult to click.
